### ISSUE TITLE
CSS Preprocessing

### ISSUE THREAD

**Issue by arggh** [meteor-svelte/meteor-svelte#15]
This repository doesn't seem to be very active, but the compiler works so I'll ask away!

Did you manage to get any kind of CSS preprocessing running with this Svelte integration?

I'd love to use PostCSS plugins with Svelte, or even use the Meteor package `nathantreid:css-modules`, which I tried, but it's throwing this kind of error in the SSR example app:

<details>
<summary>Stacktrace</summary>

```
TypeError: require(...).addStyles is not a function
W20180813-17:46:34.550(3)? (STDERR)     at App.css (components/Message.html:2:4)
W20180813-17:46:34.550(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180813-17:46:34.550(3)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180813-17:46:34.550(3)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180813-17:46:34.550(3)? (STDERR)     at App.html (/Users/arggh/Development/app/.meteor/local/build/programs/server/app/app.js:13:14)
W20180813-17:46:34.550(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180813-17:46:34.550(3)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180813-17:46:34.550(3)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180813-17:46:34.551(3)? (STDERR)     at main.js (server/main.js:1:189)
W20180813-17:46:34.551(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180813-17:46:34.551(3)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180813-17:46:34.551(3)? (STDERR)     at require (packages/modules-runtime.js:244:21)
```

</details>

**Comment by arggh** [comment]
There seems to be some npm packages which are using the Svelte compiler's preprocessor hooks, like https://github.com/tivac/modular-css/tree/master/packages/svelte#readme

**Comment by klaussner** [comment]
Thanks for the suggestion, @arggh. Preprocessing isn't supported yet because I haven't found a way to implement it without considerably increasing the maintenance overhead. Unfortunately, compiler plugins can't use peer dependencies from the app, which means that every type of preprocessing (PostCSS, Less, Sass, CoffeeScript, …) would have to be implemented in the plugin itself.

**Comment by arggh** [comment]
I managed to setup PostCSS preprocessing in such a way, that the app can determine what settings and plugins to use. If it sounds like something you'd like to take a look at, I can make a PR.

**Comment by klaussner** [comment]
Yeah, I would definitely like to take a look at your setup. 🙂 Maybe we could implement something similar to `vue-meteor`, with a separate package for each language or type of preprocessing: https://github.com/meteor-vue/vue-meteor/tree/master/packages.

**Comment by arggh** [comment]
@klaussner sorry, completely forgot about this 😳

I just pushed the branch with my stab at customizable PostCSS preprocessor + meteor-svelte: https://github.com/arggh/meteor-svelte/tree/feature/postcss

With this setup, one can customize the PostCSS pipeline from with the app, by placing config in `package.json`, and installing all the needed PostCSS plugins themselves. This should allow for pretty flexible CSS preprocessing.

What do you think about adding only support for configurable PostCSS preprocessing, and ditching the idea of Sass, Less, Stylus etc. support altogether?

**Comment by klaussner** [comment]
No worries! Thanks for sharing your repo. 🙂

To be honest, I was a little surprised that it even works because build plugins usually can't import/require packages from the app's `node_modules` directory. For example, if you try to call `require("postcss-plugin-whatever")` in `postcssProcessor.js`, Meteor will throw a `Cannot find module 'postcss-plugin-whatever'` error because it uses a custom `require` implementation (not the one provided by Node). However, npm packages apparently have access to Node's `require`, which isn't limited to the modules that Meteor knows and can even be used to require modules outside the project directory.

I don't know if that's a bug or if we can rely on this "feature" in future Meteor versions. 🤔

**Comment by arggh** [comment]
> I don't know if that's a bug or if we can rely on this "feature" in future Meteor versions.

Maybe worth bringing this up in the Meteor repo? Though I must say, I wouldn't mind having to install a separate `svelte:postcss` -package either. As long as I can benefit from some PostCSS goodness with Svelte+Meteor...

**Comment by klaussner** [comment]
Sorry for the delay. I finally found some time to look into how the `require` function works for build plugins. I thinks it's fine to use the npm package workaround until Meteor supports `require` for app-level npm packages, which is planned for a future release. From the [Meteor 1.8 release blog post](https://blog.meteor.com/meteor-1-8-erases-the-debts-of-1-7-77af4c931fe3):

> [...] Meteor compiler plugins are compiled and bundled *before* they are published to Atmosphere, which means they can end up using outdated versions of certain dependencies, unless the plugin author diligently releases new versions of the plugin. [...] **Rebuilding plugins at application build time is the general direction in which we want to move.**

I will start to work on a `svelte:postcss` package soon. 🙂

**Comment by klaussner** [comment]
Unfortunately, build plugins can't have weak dependencies on other packages, so we can't make `svelte:postcss` optional. I think PostCSS support has to be included in `svelte:compiler`, like in your fork. 🤔

**Comment by arggh** [comment]
Are there any plans on implementing the PostCSS support in `svelte:compiler`?

**Comment by arggh** [comment]
I was trying to take another stab at this, and it seems I've accidentally removed the repo linked above when cleaning up my github account, and now I can't remember how I got it to work in the first place 😂

**Comment by klaussner** [comment]
Yes, there are plans (in one or two weeks). 😄 I will probably document PostCSS support as "beta" or "experimental" because of the [undocumented Meteor quirk](https://github.com/meteor-svelte/meteor-svelte/issues/15#issuecomment-489231258) that is required to make it work.

**Comment by CaptainN** [comment]
I figured out how to load npm packages from the projects `node_modules` directory (actually, by reading Meteor Svelte's source, heh) in PR #28. Can something similar be used to enable this feature?
