### ISSUE TITLE
Cannot read property 'sections' of null (v3.44.3)

### ISSUE THREAD

**Issue by banjerluke** [meteor-svelte/meteor-svelte#52]
After updating to the latest release, I'm getting the following error when I try to run my Meteor project (mostly Blaze but with four Svelte templates, which have been working great for years):

```
/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/luke/.meteor/packages/svelte_compiler/.3.44.3.wxcc3p.dk15d++os+web.browser+web.browser.legacy+web.cordova/plugin.svelte-compiler.os/npm/node_modules/meteor/svelte-compiler/node_modules/source-map/lib/source-map-consumer.js:20:20)
    at SvelteCompiler.combineSourceMaps (packages/svelte-compiler/SvelteCompiler.js:195:27)
    at SvelteCompiler.transpileWithBabel (packages/svelte-compiler/SvelteCompiler.js:186:23)
    at SvelteCompiler.compileOneFile (packages/svelte-compiler/SvelteCompiler.js:130:19)
    at getResult (packages/caching-compiler/caching-compiler.js:305:46)
    at packages/svelte-compiler/SvelteCompiler.js:85:22
    at /Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at JsOutputResource.finalize (/tools/isobuild/compiler-plugin.js:931:12)
    at JsOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:936:10)
    at JsOutputResource.reportPendingErrors (/tools/isobuild/compiler-plugin.js:941:14)
    at ImportScanner.scanFile (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/isobuild/tools/isobuild/import-scanner.ts:1083:14)
    at /Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/isobuild/tools/isobuild/import-scanner.ts:740:14
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/isobuild/tools/isobuild/import-scanner.ts:738:22)
    at /tools/isobuild/compiler-plugin.js:1381:17
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1346:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1161:8)
    at /tools/isobuild/bundler.js:864:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3260:14
    at /tools/isobuild/bundler.js:3413:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3367:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3241:31)
    at /tools/isobuild/bundler.js:3184:32
    at Slot.withValue (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/fs/tools/fs/files.ts:1662:39)
    at Object.bundle (/tools/isobuild/bundler.js:3184:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/Users/luke/.meteor/packages/meteor-tool/.2.5.3.3lljc7.90bvp++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
```

I'm not sure what it means, but I did do a check to see if `sections` was used in any of my Svelte templates. It is not.

I will downgrade to v3.31.2 for now but I wanted to post a record of this issue.

Thanks for making this package available!

**Comment by cbaarendse** [comment]
Same here, for it happened after Meteor updates 2.5.2 and 2.5.3

**Comment by rdb** [comment]
I uploaded v3.44.3_1 which should fix the problem.
